def database():
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
    print("connect to database")
