def V3():
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")
    print("v3")